import os
import oracledb
from dotenv import load_dotenv

load_dotenv()


def get_connection():
    return oracledb.connect(
        user=os.getenv("ORACLE_USER"),
        password=os.getenv("ORACLE_PASSWORD"),
        dsn=os.getenv("ORACLE_DSN"),
    )


def initialize_database():
    connection = get_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT COUNT(*)
        FROM user_tables
        WHERE table_name = 'SENSOR_READINGS'
    """)

    table_exists = cursor.fetchone()[0] > 0

    if not table_exists:
        cursor.execute("""
            CREATE TABLE sensor_readings (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                soil_moisture NUMBER(5,2) NOT NULL,
                ph NUMBER(4,2) NOT NULL,
                nutrients_level NUMBER(5,2) NOT NULL,
                luminosity NUMBER(5,2) NOT NULL,
                temperature NUMBER(5,2) NOT NULL,
                air_humidity NUMBER(5,2) NOT NULL,

                productivity_index NUMBER(5,2) NOT NULL,
                productivity_classification VARCHAR2(20) NOT NULL,

                recommendation VARCHAR2(500) NOT NULL,
                irrigation_volume NUMBER(5,2) NOT NULL,
                fertilization_need VARCHAR2(20) NOT NULL
            )
        """)

        connection.commit()
        print("Tabela SENSOR_READINGS criada com sucesso.")

    cursor.close()
    connection.close()